/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_pcapindex_free: (a: number, b: number) => void;
export const link_preview: (a: number, b: number, c: number) => [number, number, number];
export const parse_pcap_bytes: (a: number, b: number) => [number, number, number];
export const pcapindex_addr: (a: number, b: number, c: number) => [number, number];
export const pcapindex_cap_len: (a: number, b: number, c: number) => [number, number];
export const pcapindex_complete: (a: number) => number;
export const pcapindex_count: (a: number) => number;
export const pcapindex_detail: (a: number, b: number, c: number) => [number, number];
export const pcapindex_dst_port: (a: number, b: number, c: number) => [number, number];
export const pcapindex_format: (a: number) => [number, number];
export const pcapindex_ip_version: (a: number, b: number, c: number) => [number, number];
export const pcapindex_issues: (a: number) => [number, number];
export const pcapindex_linktype: (a: number, b: number, c: number) => [number, number];
export const pcapindex_offset: (a: number, b: number, c: number) => [number, number];
export const pcapindex_orig_len: (a: number, b: number, c: number) => [number, number];
export const pcapindex_proto: (a: number, b: number, c: number) => [number, number];
export const pcapindex_src_port: (a: number, b: number, c: number) => [number, number];
export const pcapindex_summary: (a: number) => [number, number, number];
export const pcapindex_ts_nsec: (a: number, b: number, c: number) => [number, number];
export const pcapindex_ts_sec: (a: number, b: number, c: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
